#
# Makefile for the kernel FCI fc8080 TDMB device drivers.
#
#########################################################

obj-y += fc8080.o

  fc8080-y :=  bbm.o
  fc8080-y += fc8080_bb.o
  fc8080-y += fc8080_demux.o
  fc8080-y += fc8080_i2c.o
  fc8080-y += fc8080_isr.o
  fc8080-y += fc8080_ppi.o
  fc8080-y += fc8080_spi.o
  fc8080-y += fc8080_tun.o
  fc8080-y += fc8080_wrapper.o
  fc8080-y += fci_hal.o
  fc8080-y += fci_hpi.o
  fc8080-y += fci_oal.o
  fc8080-y += fci_tun.o