#
# Makefile for the kernel INC T3A00 TDMB device drivers.
#
#########################################################

obj-y += t3a00.o
  t3a00-y := t3a00_qfifo.o 
  t3a00-y += t3a00_rf_ctrl500.o
  t3a00-y += t3a00_inc_ficdec.o
  t3a00-y += t3a00_process.o
  t3a00-y += t3a00_interface.o
  t3a00-y += t3a00_bb.o