##########################################
# Makefile for MTV319 Device Drivers.
##########################################

obj-y += rtv_mtv319.o

  rtv_mtv319-y :=mtv319_bb.o
  rtv_mtv319-y += mtv319.o
  rtv_mtv319-y += mtv319_tdmb.o
  rtv_mtv319-y += mtv319_rf.o
  rtv_mtv319-y += mtv319_port.o
  rtv_mtv319-y  += mtv319_cifdec.o

